# Generated by Django 3.2.12 on 2024-11-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='information',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Write the information about topic'),
        ),
    ]
