# Generated by Django 3.2.12 on 2024-11-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syte', '0003_cars_toys'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='toys',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
