# Generated by Django 3.2.12 on 2024-11-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syte', '0004_auto_20241112_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='information',
            field=models.TextField(blank=True, max_length=550, null=True, verbose_name='Write the information about topic'),
        ),
    ]
