# Generated by Django 3.2.12 on 2024-11-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syte', '0005_alter_topic_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(choices=[('FCB', 'FACEBOOK'), ('TWT', 'TWITTER'), ('BHN', 'BEHANCE'), ('LKD', 'LINKEDIN'), ('DRB', 'DRIBBBLE')], max_length=3)),
            ],
        ),
    ]
