# Generated by Django 3.2.12 on 2024-11-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syte', '0006_contact_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='contact_links',
            field=models.ManyToManyField(to='syte.Contact_link', verbose_name='Write the available contact links'),
        ),
    ]
