# Generated by Django 3.2.12 on 2024-11-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syte', '0007_topic_contact_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='contact_links',
        ),
        migrations.AddField(
            model_name='topic',
            name='contact_links',
            field=models.CharField(choices=[('FCB', 'FACEBOOK'), ('TWT', 'TWITTER'), ('BHN', 'BEHANCE'), ('LKD', 'LINKEDIN'), ('DRB', 'DRIBBBLE')], default='FCB', max_length=3, verbose_name='Write the available contact links'),
        ),
        migrations.DeleteModel(
            name='Contact_link',
        ),
    ]
