# Generated by Django 3.2.12 on 2024-11-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syte', '0008_auto_20241116_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(choices=[('FCB', 'FACEBOOK'), ('TWT', 'TWITTER'), ('BHN', 'BEHANCE'), ('LKD', 'LINKEDIN'), ('DRB', 'DRIBBBLE')], max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='topic',
            name='contact_links',
        ),
        migrations.AddField(
            model_name='topic',
            name='contact_links',
            field=models.ManyToManyField(to='syte.Contact_link', verbose_name='Write the available contact links'),
        ),
    ]
