# Generated by Django 3.2.12 on 2024-11-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syte', '0010_topic_short_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField(max_length=255, verbose_name='Write information about your page')),
                ('donec_103', models.TextField(max_length=255, verbose_name='1-03 Donec porttitor augue')),
                ('donec_203', models.TextField(max_length=255, verbose_name='2-03 Donec porttitor augue')),
                ('donec_303', models.TextField(max_length=255, verbose_name='3-03 Donec porttitor augue')),
                ('four_01', models.TextField(max_length=255, verbose_name='01 Four Columns')),
                ('four_02', models.TextField(max_length=255, verbose_name='02 Four Columns')),
                ('four_03', models.TextField(max_length=255, verbose_name='03 Four Columns')),
                ('four_04', models.TextField(max_length=255, verbose_name='04 Four Columns')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=30, verbose_name='Write any category')),
            ],
        ),
    ]
