# Generated by Django 3.2.12 on 2024-11-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syte', '0011_about_us_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='information',
            field=models.TextField(max_length=555, verbose_name='Write information about your page'),
        ),
    ]
