# Generated by Django 3.2.12 on 2024-11-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syte', '0012_alter_about_us_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Put the Image'),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='information',
            field=models.TextField(max_length=955, verbose_name='Write information about your page'),
        ),
    ]
