# Generated by Django 3.2.12 on 2024-11-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syte', '0013_auto_20241119_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='information',
            field=models.TextField(blank=True, max_length=950, null=True, verbose_name='Write the information about topic'),
        ),
    ]
