# Generated by Django 3.2.12 on 2024-11-25 15:06

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('syte', '0014_alter_topic_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('mail', models.EmailField(max_length=254, verbose_name='Your mail')),
                ('address', models.CharField(max_length=50, verbose_name='Write your street address')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='SUBJECT'),
        ),
    ]
