# Generated by Django 3.2.12 on 2024-11-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syte', '0017_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=30, verbose_name='Write tha tags')),
            ],
        ),
    ]
